name: Bild Web and deploy to GH pages
on: 
  push:
    branches: 
      - master
 #wenn ich auf Master pushe, dann wird es ausgeführt
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
#ich möchste auf Betriebssystem ubuntu arbeiten  unbunu console geöffnet
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
#Release to Gh-Pages
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree public add --all
      - run: git commit -m "Automatic deployment by Github Action"
      - run: git push origin HEAD:git-pages --force