name: Bild Web and deploy to GH pages
on: push
  #branches: 
        #- main
 #wenn ich auf Master pushe, dann wird es ausgeführt
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
#ich möchste auf Betriebssystem ubuntu arbeiten  unbunu console geöffnet
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: git-pages
      - run: ls -l